name: Deploy-Prod
on:
  workflow_dispatch:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}
env:
  ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}
  TARGET_ENV: 'Prod'
  TARGET_AWS_REGION: us-east-1
  AWS_ACCOUNT_ID_LIST_FOR_LB: ${{ secrets.PROD_AWS_ACCOUNT_ID_LIST_FOR_LB }}
  SLACK_ADMIN_USER_ID_LIST: ${{ vars.PROD_ADMIN_USER_ID_LIST }}
  ROLE_NAME_FOR_LB: ${{ vars.PROD_ROLE_NAME_FOR_LB }}
  WORKER_ADDITIONAL_POLICIES: ${{ secrets.PROD_WORKER_ADDITIONAL_POLICIES }}
  GITHUB_APP_ID: ${{ secrets.PROD_GITHUB_APP_ID }}
  GITHUB_INSTALLATION_ID: ${{ secrets.PROD_GITHUB_INSTALLATION_ID }}
  ENABLE_LAMBDA_WARMER: true
jobs:
  Deploy-cdk:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: add-mask
        run: |
          echo "::add-mask::${{ secrets.PRODACCOUNTID }}"
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: gha-session
          aws-region: ${{ env.TARGET_AWS_REGION }}
      - run: |
          npm ci
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          npx cdk deploy --all --require-approval never
        working-directory: ./cdk
        name: build and deploy CDK
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
